# Generated by Django 4.2 on 2023-05-26 01:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adsname', models.CharField(max_length=300)),
                ('adsimg', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='FreeBeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beatname', models.CharField(max_length=200)),
                ('beatfile', models.FileField(upload_to='music')),
                ('beatimg', models.ImageField(upload_to='image')),
                ('created', models.TimeField(default=datetime.datetime(2023, 5, 26, 2, 11, 20, 609569))),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musicname', models.CharField(max_length=200)),
                ('artistname', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='music')),
                ('musicimg', models.ImageField(upload_to='image')),
                ('created', models.TimeField(default=datetime.datetime(2023, 5, 26, 2, 11, 20, 609569))),
            ],
        ),
    ]
