# Generated by Django 4.2 on 2023-05-26 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsvibe_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='adsdescription',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='freebeat',
            name='created',
            field=models.TimeField(default=datetime.datetime(2023, 5, 26, 2, 54, 16, 435838)),
        ),
        migrations.AlterField(
            model_name='music',
            name='created',
            field=models.TimeField(default=datetime.datetime(2023, 5, 26, 2, 54, 16, 435838)),
        ),
    ]
