# Generated by Django 4.2 on 2023-05-27 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsvibe_app', '0004_alter_freebeat_created_alter_music_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freebeat',
            name='beatartistname',
            field=models.CharField(default='test', max_length=230),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='freebeat',
            name='created',
            field=models.TimeField(default=datetime.datetime(2023, 5, 27, 10, 8, 24, 929018)),
        ),
        migrations.AlterField(
            model_name='music',
            name='created',
            field=models.TimeField(default=datetime.datetime(2023, 5, 27, 10, 8, 24, 929018)),
        ),
        migrations.AlterField(
            model_name='video',
            name='created',
            field=models.TimeField(default=datetime.datetime(2023, 5, 27, 10, 8, 24, 929018)),
        ),
    ]
